-- sql/00_setup.sql
CREATE OR REPLACE WAREHOUSE WEATHER_TWIN_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE WEATHER_TWIN_DB;

CREATE OR REPLACE SCHEMA WEATHER_TWIN_DB.RAW;
CREATE OR REPLACE SCHEMA WEATHER_TWIN_DB.APP;

USE DATABASE WEATHER_TWIN_DB;
USE SCHEMA RAW;

SELECT CURRENT_VERSION();